# Generated by Django 3.2.5 on 2021-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('name_file', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('posX', models.IntegerField()),
                ('posY', models.IntegerField()),
                ('tipo', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
