# Generated by Django 3.2.5 on 2021-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista3D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
